### PR TITLE
Remove ansi for c++11

### PR DESCRIPTION
**Pull request by petricm**
Remove the -ansi -Werror flag. ansi interferes with c++11 and Werror makes problems in compilation.

### CODE REVIEW

**Comment by PandoraPFA** [comment]
Hi Marko,

I agree that, with -std=c++11, you'd want to remove/replace -ansi (equivalent to -std=c++03, I think).

There might be something cleaner that can be done within the complex logic of the following: https://github.com/PandoraPFA/PandoraSDK/blob/master/CMakeLists.txt#L27

Note that we'd ultimately like to drop support for anything prior to c++11, as we have for all our LAr TPC algorithms. Compare the following:
https://github.com/PandoraPFA/LArContent/blob/master/CMakeLists.txt#L99 vs.
https://github.com/PandoraPFA/LCContent/blob/master/CMakeLists.txt#L43

I'm not convinced about removing -Werror, however. The intention here is surely just to force you to address errors immediately, which is a good thing?!

Cheers,

John

P.S. I'm at a workshop today, so may not be able to reply to this thread again immediately.

**Comment by petricm** [comment]
Hi,
You can also introduce a flag for c++11 which disables ansi?
At the moment given the current state -Werror breaks the MarlinPandora compilation.
Cheers,
Marko

CC:@andresailer

**Comment by petricm** [comment]
Hi,
so what is the decision regarding this?
Please remove at least -Werror from MarlinPandora.
Cheers,
Marko

**Comment by PandoraPFA** [comment]
Hi Marko,

I flagged this to follow-up, but have extremely limited availability at the moment, with a number of back-to-back workshops and a conference.

Hopefully @bonoxu will be able to help you with the MarlinPandora issue. I am loath to remove the -WError flag unless strictly necessary (we may not be discussing this issue if the flag wasn't present, doing its job!).

What is the compile-time error, how can we reproduce it and do you know why we haven't seen it before with any of the existing ilcsoft gcc 4.8 builds, with std=c++11 selected?

Hopefully Bono can help - thanks Bono!

Best wishes,

John

**Comment by petricm** [comment]
Hi,
the default compiler flags for iLCSoft have changed and are defined in iLCUtil now as
-Wall -Wextra -Wshadow -Weffc++ -pedantic -Wno-long-long -Wuninitialized

MarlinPandora is
-Wall -Werror -ansi -pedantic -Wno-long-long -Wno-sign-compare -fno-strict-aliasing

Especially "-Wextra -Wshadow -Weffc++" adds a lot of new warnings. It is meant that developers with time address these warnings, but they are not few.

Cheers,
Marko

**Comment by petricm** [comment]
Any news on `c++11` integration?

**Comment by PandoraPFA** [comment]
Hi,

What exactly do you need? Presumably you're interested in the list of cxx flags in the Pandora CMake build, which does probably need a quick overhaul?

The PandoraSDK and various algorithm libraries do now use c++11 functionality throughout, although only the newer algorithms are fully embracing move semantics, etc.

The ansi cxx flag, therefore, now must be overridden by e.g. a -std=c++11 or 14 or 1y flag later (i.e. rightmost, I think?) in the list. Is removal of the ansi flag all that you require? (It's currently pointless, but easy to override).

Cheers,

John

**Comment by petricm** [comment]
For us it would be more then enough if you drop `-ansi` and just require `c++11`.

**Comment by PandoraPFA** [comment]
OK, will aim to do just this, but obviously need to test out the LArSoft use-case too (probably tomorrow).
I think it will be just fine.

**Comment by PandoraPFA** [comment]
Should now be as you want it. Please just let us know if there's anything that doesn't work as expected.

Thanks!

**Comment by petricm** [comment]
Thank you this should be fine. However, just as a suggestion, it might be a more general implementation via `CMAKE_CXX_STANDARD` this is then easier steerable over several projects.

**Pull request closed without merging**
