### PR TITLE
ClusterFitHelper : removed cout

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Removed cout on cluster fit fail

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
This cout is massively called in the ILD reconstruction and can't be shut down by using streamlog. There is also no possiblity to use PandoraSettings::ShouldDisplayAlgorithmInfo() to decide of the printout.

**Comment by rete** [comment]
TravisCI failing for some obscure reason ...

**Comment by PandoraPFA** [comment]
Looked like networking issues in the first Travis build attempt; the build was successful when restarted.

Pretty much happy to remove this (it would otherwise need a configurable on/off, at least), but do quickly want to query how often you see failed fits? What does "massively" mean? :)

If I recall correctly, this message was quite rare in the old days of Mokka, MarlinPandora, etc. The fits do use e.g. the cell normal vectors to define a sensible coordinate system, so are these definitely all OK? (there were some issues with the normal vectors in the early days of DDMarlinPandora, I think).

There are many other reasons for failed fits, though, such as trying to fit clusters with few hits, or few layers. The idea was that the algorithms would work to stop calling functions that fail e.g. check number of hits before trying to fit, but inputs can (obviously) change for a given algorithm.

If you're happy with the observed internal fit failure rate, then will merge.

**Comment by rete** [comment]
The rate failure in our ttbar test samples (3 events) in ILDConfig show regularly this message. Depending on the event, it can be from 2 printout up to 30 by event. If the algorithms take care of handling the error correctly, there is no reason to keep it in the ClusterFitHelper. The algorithms can catch the error and print something using the PandoraSettings::ShouldDisplayAlgorithmInfo() for example if needed.
It the current state and if you agree, it can be merged.

**Pull request merged**
